name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install meson
      run: |
        sudo apt-get update
        sudo apt-get install -y meson libprotobuf-c-dev libfuse3-dev
    - name: Install Jitter RNG
      run: |
        wget -O jent.tar.gz https://github.com/smuellerDD/jitterentropy-library/archive/refs/tags/v3.4.1.tar.gz
        tar xvfz jent.tar.gz
        make -C jitterentropy-library*
        sudo make -C jitterentropy-library* install
        sudo ldconfig
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
