name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install meson
      run: |
        sudo apt-get update
        sudo apt-get install -y meson libprotobuf-c-dev libfuse3-dev
    - name: Install Jitter RNG
      run: |
        wget -O jent.tar.gz https://github.com/smuellerDD/jitterentropy-library/archive/refs/tags/v3.4.1.tar.gz
        tar xvfz jent.tar.gz
        make -C jitterentropy-library*
        sudo make -C jitterentropy-library* install
        sudo ldconfig
    - name: Install ESDM
      run: |
        wget -O esdm.tar.gz https://github.com/smuellerDD/esdm/archive/da9304dc0682c82dfe3f83407984e2333c16b3ea.tar.gz
        tar xvfz esdm.tar.gz
        cd esdm-*
        meson setup build -Dselinux=disabled -Dais2031=false
        meson compile -C build
        sudo meson install -C build
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
